### ISSUE TITLE
Channel8 new consoles modes to your ConsoleMM module feature request 

### ISSUE THREAD

**Issue by vcvrackideas** [n0jo/rackwindows#10]
Just watched a Chris' video on his new module and finally I can hear that impact (probably with help of Driver knob, don't sure) of console to the tracks. So if you can implement this to your module (or make a new one with DRIVE knobs for instance...) that would be MORE than just fun. Cheers! http://www.airwindows.com/channel8/

**Comment by n0jo** [comment]
I'm not sure, could it be that you confuse Channel with Console? They both aim to "analogify", but are otherwise quite different. 

For what it's worth the latest development version of Console has a Drive knob now to help adjust the effect to taste.

**Comment by vcvrackideas** [comment]
> I'm not sure, could it be that you confuse Channel with Console? They both aim to "analogify", but are otherwise quite different.
> 
> For what it's worth the latest development version of Console has a Drive knob now to help adjust the effect to taste.

Sorry Jens I was wrong. Exactly. And now I'm testing your Console with Drive knob and noticing that drive knob actually affects only polyphonic outputs because I tested it with two options processed and unprocessed sum outputs and it only works with processed which is cool and working as expected. But nothing changes in terms of distortion and levels (which should be significant for sure according for what's going on with SUM outputs). So I think that the Drive knob doesn't affect main LR output right now, is it right? Correct me if I wrong. Cheers! ;-) And thanks for implementing this. A bit of saturation in the end of a chain is amazing thing to improve whole patch! And of course it's not an ordinary saturator - it's like console summing.

**Comment by airwindows** [comment]
> On 9 10, 2020, at 2:35 PM, VCV Rack Ideas <notifications@github.com> wrote:
> For what it's worth the latest development version of Console has a Drive knob now to help adjust the effect to taste.

	If you’re talking about the summing system, Console, there can be an input trim on inputs, but it does not adjust the effect.

	CHANNEL has a drive knob, that adjusts an effect to taste (all versions of Channel have this in one way or another)

	Console has an input gain knob that is the same as having a fader on that input. It leaves the effect the same (only relevant when multiple inputs are being summed) and gain-stages the input relative to the output of the mix you get. That’s not adjusting the effect, that’s just making a mix: the effect is fixed and replaces the digital summing buss with a different algorithm.

	Chris

**Comment by n0jo** [comment]
I think that's a misunderstanding, Chris. The next Rackwindows release includes a module called Console MM (to work specifically  in conjunction with Mindmeld's MixMaster module), which can be over- or underdriven. I believe that's what @vcvrackideas was referring to.
