### ISSUE TITLE
Artwork license question

### ISSUE THREAD

**Issue by falkTX** [n0jo/rackwindows#15]
Just a quick question, as I don't see it mentioned anywhere.
Your project is licensed under MIT, same as the original airwindows project. But what about the panel graphics, are those also MIT licensed? Or are they supposed to be in a different license?
Thanks!

**Comment by n0jo** [comment]
Hi! The graphics are meant to be MIT too. Perhaps it should be stated explicitly, I guess.

**Comment by falkTX** [comment]
Ah that is good to know. Yeah typically the software and artwork license is not the same, so I wanted to ask to make sure.
Do as you see best, my point was just to clarify this.
Thanks again.
