### ISSUE TITLE
Dual BSG doesn't render switch under linux

### ISSUE THREAD

**Issue by ContemporaryInsanity** [n0jo/rackwindows#2]
![image](https://user-images.githubusercontent.com/12547379/79068209-1dde6a00-7cbd-11ea-8aaa-b8dc7a830cbf.png)

Filename error in components.hpp:

// switches
struct CKSSRot : SvgSwitch {
    CKSSRot()
    {
        addFrame(APP->window->loadSvg(asset::plugin(pluginInstance, "res/components/CKSS_rot_0.svg")));
        addFrame(APP->window->loadSvg(asset::plugin(pluginInstance, "res/components/CKSS_rot_1.svg")));
    }
};

![image](https://user-images.githubusercontent.com/12547379/79068295-c2f94280-7cbd-11ea-877b-314e8ebc2417.png)

**Comment by n0jo** [comment]
Thanks, I'll look into it.

**Comment by SteveRussell33** [comment]
Same on Windows, changing the filenames in ``components.hpp`` renders the switch properly.

**Comment by n0jo** [comment]
Thanks guys, should be fixed. Please let me know if the error persists on your end.
