### ISSUE TITLE
Crashes Rack when opening module browser

### ISSUE THREAD

**Issue by Ananda6262** [n0jo/rackwindows#3]
Win 10 Home
rack v1.1.6
"[3.893 info src/window.cpp:72] Loaded SVG C:\Users\Ananda\DOCUME~1/Rack/plugins- 
            v1/rackwindows/res/bitshiftgain_dark.svg
[4.438 fatal src/main.cpp:45] Fatal signal 4. Stack trace:
            23: ZN4rack10appDestroyEv 0x456435"

[log.txt](https://github.com/n0jo/rackwindows/files/4470359/log.txt)

**Comment by SteveRussell33** [comment]
Can't reproduce this on my Win 10 machine. Don't know if it'll help, try the fix for the missing switch here https://github.com/n0jo/rackwindows/issues/2#issuecomment-613148254

**Comment by n0jo** [comment]
Same here. But I agree, it's likely related to the faulty filenames of the vertical switch. Please try again if you find the time.

**Comment by Ananda6262** [comment]
I deleted rackwindows from my plugin directory which needless to say solves my dilemma.
