### ISSUE TITLE
Build error with fix [Win 10] 

### ISSUE THREAD

**Issue by SteveRussell33** [n0jo/rackwindows#4]
g++ -std=c++11 -Wsuggest-override  -fPIC -I../../include -I../../dep/include -MMD -MP -g -O3 -march=nocona -funsafe-math-optimizations -Wall -Wextra -Wno-unused-parameter -DARCH_WIN -D_USE_MATH_DEFINES  -c -o build/src/bitshiftgain.cpp.o src/bitshiftgain.cpp

src/bitshiftgain.cpp: In constructor 'BitshiftgainWidget::BitshiftgainWidget(Bitshiftgain*)':
src/bitshiftgain.cpp:225:38: error: 'CKSSRot' was not declared in this scope; did you mean 'RwCKSSRot'?
  225 |         addParam(createParamCentered<CKSSRot>(Vec(30.0, 195.0), module, Bitshiftgain::LINK_PARAM));
      |                                      ^~~~~~~
      |                                      RwCKSSRot
src/bitshiftgain.cpp:225:97: error: no matching function for call to 'createParamCentered<<expression error> >(rack::math::Vec, Bitshiftgain*&, Bitshiftgain::ParamIds)'
  225 |         addParam(createParamCentered<CKSSRot>(Vec(30.0, 195.0), module, Bitshiftgain::LINK_PARAM));
      |                                                                                                 ^
In file included from ../../include/rack.hpp:16,
                 from src/components.hpp:2,
                 from src/plugin.hpp:2,
                 from src/bitshiftgain.cpp:21:
../../include/helpers.hpp:71:15: note: candidate: 'template<class TParamWidget> TParamWidget* rack::createParamCentered(rack::math::Vec, rack::engine::Module*, int)'
   71 | TParamWidget* createParamCentered(math::Vec pos, engine::Module* module, int paramId) {
      |               ^~~~~~~~~~~~~~~~~~~
../../include/helpers.hpp:71:15: note:   template argument deduction/substitution failed:
src/bitshiftgain.cpp:225:97: error: template argument 1 is invalid
  225 |         addParam(createParamCentered<CKSSRot>(Vec(30.0, 195.0), module, Bitshiftgain::LINK_PARAM));
      |                                                                                                 ^
make: *** [../../compile.mk:69: build/src/bitshiftgain.cpp.o] Error 1
make: *** Waiting for unfinished jobs....

Changing line https://github.com/n0jo/rackwindows/blob/94b4863eda46380c0ca815f3a33c39de96d1b3a0/src/bitshiftgain.cpp#L225 to ``        addParam(createParamCentered<RwCKSSRot>(Vec(30.0, 195.0), module, Bitshiftgain::LINK_PARAM));``
solves this.

**Comment by davephillips** [comment]
@SteveRussell33 Thanks for that, it fixed the same error on Linux, Ubuntu 18.04.

**Comment by n0jo** [comment]
Thanks @SteveRussell33 , line is fixed (in the correct branch this time around).

**Comment by SteveRussell33** [comment]
No worries guys, glad to help.

Closing.
