### ISSUE TITLE
Tape low cpu mode

### ISSUE THREAD

**Issue by vcvrackideas** [n0jo/rackwindows#5]
Hi and finally tape is here and thank you for that! It sounds awesome, it has some bottom feeling and nice and pleasent processing to any waveform according to scope. But CPU consumption is around 10 percent. Is it possible to implement a LOW CPU mode for example as Plaits or Braids have? So in that way we can apply it during patch building and when recording just deselect it to get full high resolution of tape's processing. Thanks again!

**Comment by n0jo** [comment]
@vcvrackideas Man, your quick :-) Thanks for the feedback. 

Tape features a collection of Airwindows algorithms (e.g. Biquad, UnBox, Spiral, ADClip, 32bit floating point dither) and is therefore certainly rather CPU hungry. On top of that the module is stereo and polyphonic. I'll definitely look for ways to optimize the module though, but wouldn't want to alter actual Airwindows code and risk sacrificing what makes Tape sound great in the first place. I'll see what I can do.

**Comment by n0jo** [comment]
Will close this for now. A low CPU option has been added, which improves performance by 10-15% at the cost of slightly worse audio quality. Tape is very heavy still and should be optimized further down the road though.
