### ISSUE TITLE
Various notes on ported modules

### ISSUE THREAD

**Issue by stoermelder** [n0jo/rackwindows#6]
I selected one of the modules randomly and did a quick review. I guess most of the points apply to mose or all of the other modules. Maybe some of the following need to be discussed in separate issues so feel free to split them up:

- https://github.com/n0jo/rackwindows/blob/9fc1411e428aba6949a3d262e7aaf210b61f1667/src/distance.cpp#L13 You should be careful with this sentence. The component library is [licenced](https://github.com/VCVRack/Rack/blob/v1/LICENSE.md) under CC BY-NC-ND 4.0 which doesn't derivative works.

- https://github.com/n0jo/rackwindows/blob/9fc1411e428aba6949a3d262e7aaf210b61f1667/src/distance.cpp#L81 This is the wrong place for initialization of local variables. You should move this code to `onReset` or `resetNonJson` if you like. 

- https://github.com/n0jo/rackwindows/blob/9fc1411e428aba6949a3d262e7aaf210b61f1667/src/distance.cpp#L106 I think you should add a call to `updateParams` here.

- https://github.com/n0jo/rackwindows/blob/9fc1411e428aba6949a3d262e7aaf210b61f1667/src/distance.cpp#L93 I'm not convinced by this calculation. Are you sure you don't need the reciprocal here? I did a quick test and it seems I might be right...

- https://github.com/n0jo/rackwindows/blob/9fc1411e428aba6949a3d262e7aaf210b61f1667/src/distance.cpp#L76 Was it a deliberate decision to set the divisions to 2? In the VSTs these values are calculated at every block which is much far less usually, for example 32 or 64 samples. Maybe link the number of divisions to the quality setting?

**Comment by n0jo** [comment]
Thanks a lot for taking the time, Ben. Very much appreciated. 

> You should be careful with this sentence. The component library is licenced under CC BY-NC-ND 4.0 which doesn't derivative works.

Will have to look into that. Actually most UI elements have been replaced with custom ones over time, so maybe the sentence doesn't even hold true anymore. Do you think it's a violation if an element from the library is used in rotated form though, like the CKSS switch in Chorus for example?

> This is the wrong place for initialization of local variables. You should move this code to onReset or resetNonJson if you like.

Didn't know that, thanks. Will move. Same for updateParams.

> I'm not convinced by this calculation. Are you sure you don't need the reciprocal here? I did a quick test and it seems I might be right...

Hmmm, looks correct to me and apparently works fine in VST and AU, but I could be wrong of course. What exactly did you test and which behaviour were you looking for? Either way, I'm gonna make an issue just for this matter until a solution to the faulty sample rate scaling in general is found.

> Was it a deliberate decision to set the divisions to 2? In the VSTs these values are calculated at every block which is much far less usually, for example 32 or 64 samples. Maybe link the number of divisions to the quality setting?

Yes, it was meant for larger blockwise calculations, but honestly I'm not sure if it's worth keeping around at all. It mostly applies to variables that need to be updated on parameter changes and - in my tests - this has to happen at least every second sample for smooth enough modulation with most modules.  So yeah, kinda defeats it's purpose if used like that.

Thanks again for your input. I'm somewhat rusty when it comes to C++ and programming in general so any help is more than welcome.

**Comment by stoermelder** [comment]
> What exactly did you test and which behaviour were you looking for? Either way, I'm gonna make an issue just for this matter until a solution to the faulty sample rate scaling in general is found.

It might be the cause of the sample rate issue. The test I did: I changed the line to `overallscale = 1.f / overallscale;` in the Chorus module and moved the Speed knob and Range knob to max. Then I switched the engine's sample rate setting to different settings. The sound should stay more or less the same but with the orginal code it changed quite much, the modified version kept sounding the same.

**Comment by n0jo** [comment]
Ugh, it's been a while. I've been neglecting this issue a bit, mostly because - for better or worse - the modules seem to handle sample rates just like the VST/AU plugins after all (before, a silly mistake in the Reaper settings led me to believe otherwise). Therefore varying behaviours at different sample rates derive from the Airwindows code itself and I'm leaning towards leaving it as is, since it's not a major problem, just something to keep in mind.

Closing for now, but will reopen if I decide to make adjustments.

**Comment by stoermelder** [comment]
Thanks for the info. I will contact Chris directly as to discuss the samplerate issue.
