### ISSUE TITLE
Feature Request: RackWindows Console, but for MindMeld Poly Direct outs

### ISSUE THREAD

**Issue by Chaircrusher** [n0jo/rackwindows#7]
This may seem niche, but I think this would be a huge win for a LOT of people's usual workflow.

In testing the RackWindows Console I used the "1-8" and "Grp/Aux" polyphonic outputs into a Split module, then routed the mono channels into Console.  Then the stereo output of RackWindows right into Audio 8.  The default setting for direct outs on AirWindows means that you get the output of the Mixmaster after all channel fades.

So the output of RackWindows Console is basically the same (but different!) than the master bus of Mixmaster at unity gain.

So a "Mindmeld Edition" of Console would have:
1. 3 poly inputs - 1-8, 9-16, and Grp/Aux
2. Each poly input would treat the input like 8 stereo pairs.
3. Sum all 48(!) inputs to OUT L and OUT R.
4. Obviously, don't process unconnected inputs.

What say you?  I'm going to log a feature request for MindMeld; they could do this as an expander, and optimize to bypass unconnected inputs.

**Comment by n0jo** [comment]
Great idea. Being able to use Console in conjunction with MM like that could be neat. I'll report back when I've got something for you to test.

**Comment by n0jo** [comment]
@Chaircrusher Please check this [development release](https://github.com/n0jo/rackwindows/releases/tag/v1.1.2-beta.2) if you like and let me know what you think. Seems like your idea will lead to a neat little symbiosis of MixMaster and Console, especially if the MindMeld guys complete the roundtrip by adding an option to go back into MM's chain input.

**Comment by n0jo** [comment]
Closing as the feature has been implemented and is available in the library.
